services:
  app:
    #image: registry.gitlab.com/antoine.gueheneuc/doc-cs2i
    image: ghcr.io/anto-nwar/doc-cs2i
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - published: 8080
      target: 80
